Add SubTB objective + valence checks
recursionpharma/gflownet pull request #39
Opened 2022-12-14 17:07 UTC by bengioe

This PR has two major contributions plus some housekeeping.
- Adds the SubTrajectory Balance objective [1]
- Adds valence checks to the atom environment

Housekeeping:
- Readme updates
- rewards are no longer passed around on a linear scale, but instead on a log scale (relevant when using low temperatures)
- add a FiLM-like shift & scale operation as a function of conditioning inputs to the base architecture
- reorganize how logits are generated in the model class, this is to be compatible with different environments
- remove dependency on determined in callbacks
- add `start_at_step` hyperparameter in `GFNTrainer`
- makes some computations optional in the multiobjective statistics hook
- allow keyword arguments in multiprocessing proxy

[1] [Learning GFlowNets from partial episodes for improved convergence and stability, Kanika Madan, Jarrid Rector-Brooks, Maksym Korablyov, Emmanuel Bengio, Moksh Jain, Andrei Nica, Tom Bosc, Yoshua Bengio, Nikolay Malkin](https://arxiv.org/abs/2209.12782)

2022-12-14 21:07 UTC, bengioe commented
@bearnshaw this is kind of two PRs in one. Let me know if I should split this one up in two (or more) pieces.

The build is currently failing because of a security vulnerability in a dependency, any thoughts on how to proceed?

2022-12-14 21:35 UTC, bearnshaw commented
> The build is currently failing because of a security vulnerability in a dependency, any thoughts on how to proceed?

Can you update the dependency?

2022-12-14 22:10 UTC, bengioe commented
> Can you update the dependency?

The dependency is mpmath which comes through sympy, used by MXMNet which we've used in the past as the proxy for QM9 experiments. It seems like the issue has been patched on the trunk of mpmath but no new version has been released (including on nexus). We could remove the explicit sympy dependency and raise an exception telling users to manually install sympy if they want to run QM9 experiments.

2022-12-20 23:37 UTC, bearnshaw requested changes

2022-12-20 23:37 UTC, bearnshaw commented on src/gflownet/algo/trajectory_balance.py
> +        ]
I think it would be helpful to extend the docstring and say in words what this code is doing.

2022-12-20 23:37 UTC, bearnshaw commented on src/gflownet/algo/trajectory_balance.py
> +    def subtb_loss_fast(self, P_F, P_B, F, R, traj_lengths):
Same here - add a docstring that describes in words what the code is doing.

2022-12-20 23:37 UTC, bearnshaw commented on src/gflownet/envs/graph_building_env.py
> +            assert action.attr not in gp.nodes[action.source] or gp.nodes[action.source][action.attr] is None
Add a comment that explains the edge case addressed here.

2023-01-11 21:43 UTC, bengioe commented
@bearnshaw Pushed some comments to explain how the SubTB objective is computed, let me know if that clarifies things.

2023-01-18 20:23 UTC, bearnshaw commented on src/gflownet/algo/trajectory_balance.py
> +    def subtb_loss_fast(self, P_F, P_B, F, R, traj_lengths):
Thanks for doing this! However, comments usually proceed the code, not follow. Would you please change the order?

2023-01-18 20:24 UTC, bearnshaw approved these changes

2023-01-18 20:24 UTC, bearnshaw commented on src/gflownet/algo/trajectory_balance.py
> +    def subtb_loss_fast(self, P_F, P_B, F, R, traj_lengths):
Looks good, thanks!

2023-01-18 20:24 UTC, bearnshaw commented on src/gflownet/envs/graph_building_env.py
> +            assert action.attr not in gp.nodes[action.source] or gp.nodes[action.source][action.attr] is None
Looks good, thanks!

2023-01-19 15:05 UTC, merged