Add random walk features to atom-env
recursionpharma/gflownet pull request #50
Opened 2023-02-14 16:04 UTC by bengioe

Adds:
- the ability compute random walk features of graph nodes, this is known to help GNNs' representational power
- these features by default to the atom environment context

2023-02-20 23:42 UTC, bearnshaw commented
What are random walk features? Is there a reference you could share?

2023-02-21 17:13 UTC, bengioe commented
Good point, as far as I know [this is where they were introduced](https://arxiv.org/abs/2110.07875), they also made their way into the recent SoTA [GraphGPS](https://arxiv.org/abs/2205.12454) paper.

2023-03-07 20:20 UTC, bearnshaw requested changes
Looks good, one requested change.

2023-03-07 20:20 UTC, bearnshaw commented on src/gflownet/utils/graphs.py
> +    for k in range(k):
```suggestion
    for _ in range(k):
```
It's more pythonic to use `_` in a dummy loop.

2023-03-16 19:05 UTC, bearnshaw approved these changes

2023-03-20 14:47 UTC, merged